name: Maven TestNG CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-remote-lambdatest:
    name: Test (LambdaTest Grid)
    runs-on: ubuntu-latest
    env:
      # These must be set as GitHub Secrets:
      # Settings → Secrets and variables → Actions → New repository secret
      LT_USERNAME: ${{ secrets.LT_USERNAME }}
      LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
      MAVEN_OPTS: "-Dmaven.wagon.httpconnectionManager.ttl=60 -Djava.awt.headless=true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build (skip tests)
        run: mvn -B -ntp -DskipTests package

      - name: Verify LT secrets
        run: |
          if [ -z "$LT_USERNAME" ] || [ -z "$LT_ACCESS_KEY" ]; then
            echo "::error::LT_USERNAME or LT_ACCESS_KEY is not set as a secret."
            exit 1
          fi

      - name: Run tests (TestNG suite)
        run: mvn -B -ntp test

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            target/surefire-reports/**
            target/*.log
          retention-days: 14

  # ---------------------------------------------
  # OPTIONAL: Local headless Chrome run
  # Enable this job if you switch your test code
  # to the local ChromeDriver block.
  # ---------------------------------------------
  # test-local-headless:
  #   name: Test (Local Headless)
  #   runs-on: ubuntu-latest
  #   env:
  #     MAVEN_OPTS: "-Dmaven.wagon.httpconnectionManager.ttl=60 -Djava.awt.headless=true"
  #     CHROME_BIN: "/usr/bin/google-chrome"
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Set up Java 17
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: temurin
  #         java-version: "17"
  #         cache: maven
  #
  #     - name: Install Google Chrome
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y wget gnupg
  #         wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux.gpg
  #         echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
  #         sudo apt-get update
  #         sudo apt-get install -y google-chrome-stable
  #         google-chrome --version
  #
  #     - name: Build (skip tests)
  #       run: mvn -B -ntp -DskipTests package
  #
  #     - name: Run tests locally (headless)
  #       run: mvn -B -ntp -Dtest=tests.GoogleTest test
  #
  #     - name: Upload Surefire reports
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: surefire-reports-local
  #         path: |
  #           target/surefire-reports/**
  #           target/*.log
  #         retention-days: 14
